### PR TITLE
Update actions to node 16

### PR DESCRIPTION
**Pull request by filosganga**

### CODE REVIEW

**Comment by filosganga** [comment]
@alehechka Any chance to have this merged? 🙇🏼‍♂️

**Comment by filosganga** [comment]
Thank you @alehechka, do you plan to release a v2 with this last change at some point?

**Comment by alehechka** [comment]
@filosganga I can. Gonna make these same changes to the download-tartifact action then release a new version of both.

**Comment by filosganga** [comment]
Thank you very much

**Pull request merged**
